# Generated by Django 2.0 on 2018-01-27 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Exerciser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='runtracker.Exerciser')),
                ('exercisers', models.ManyToManyField(to='runtracker.Exerciser')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('duration', models.DurationField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtracker.Activity')),
                ('evt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runtracker.Event')),
                ('exerciser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtracker.Exerciser')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='exerciser',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='runtracker.State'),
        ),
        migrations.AddField(
            model_name='exerciser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator+', to='runtracker.Exerciser'),
        ),
        migrations.AddField(
            model_name='event',
            name='exercisers',
            field=models.ManyToManyField(to='runtracker.Exerciser'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='runtracker.State'),
        ),
    ]
