# Generated by Django 2.0 on 2018-01-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
