# Generated by Django 2.0 on 2018-01-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0002_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='exercisers',
            field=models.ManyToManyField(null=True, to='runtracker.Exerciser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
