# Generated by Django 2.0 on 2018-02-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtracker', '0010_auto_20180130_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='evt',
            new_name='event',
        ),
    ]
