# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4-browsers
        environment:
          PGHOST: 127.0.0.1
          TEST_DB: circle_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

#      - image: selenium/standalone-firefox:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mkdir geckodriver
            wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
            tar -xvf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
            sudo cp geckodriver/geckodriver /usr/local/bin/

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            python manage.py test runtracker

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: run server
          command: |
            . venv/bin/activate
            python manage.py runserver
          background: true

      - run:
          name: run functional tests
          command: |
            . venv/bin/activate
            python manage.py test vacationrun

      - store_artifacts:
          path: test-reports
          destination: test-reports
